pipeline {
    agent none
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '8', daysToKeepStr: '20'))
        timeout(time: 1, unit: 'HOURS')
    }
    stages {
        stage('main') {
            agent {
                dockerfile {
                    dir 'ci'
                    args '--gpus 1'
                }
            }
            environment {
                HOME = "${WORKSPACE}"
                PYPATH = "${WORKSPACE}/.local/bin"
                LC_ALL = "C"
                MKL_THREADING_LAYER = "GNU"
                PVFMM_DIR = "/usr/local/share/pvfmm"
                LD_LIBRARY_PATH = "/opt/intel/oneapi/mkl/latest/lib/intel64:/usr/local/lib"
                OMP_NUM_THREADS = "4"
            }
            steps {
                sh 'printenv | egrep "(^HOME|^PATH|^STKFMM_ROOT|^MKLROOT|^LD_LIBRARY_PATH|^pvfmm_DIR|^MKL_THREADING_LAYER|^LC_ALL|^CXX_FLAGS_|&PVFMM_DIR)"'
                sh 'python3 -m pip install --user ".[tests]"'
                sh 'git submodule update --init'
                sh 'cmake -B build . -DCMAKE_BUILD_TYPE=Release \
                    -DCMAKE_CXX_FLAGS="$CXXFLAGS_" -DBLAS_LIBRARIES=$MKLROOT/lib/intel64/libmkl_rt.so \
                    -DLAPACK_LIBRARIES=$MKLROOT/lib/intel64/libmkl_rt.so -GNinja'
                sh 'ninja -C build'
                sh 'cd build && ctest --output-on-failure'
                sh 'PATH=$PYPATH:$PWD/build:$PATH python3 -m pytest tests --verbose'
            }
        }
    }
    post {
        failure {
            emailext subject: '$PROJECT_NAME - Build #$BUILD_NUMBER - $BUILD_STATUS',
	        body: '''$PROJECT_NAME - Build #$BUILD_NUMBER - $BUILD_STATUS
Check console output at $BUILD_URL to view full results.
Building $BRANCH_NAME for $CAUSE
$JOB_DESCRIPTION
Changes:
$CHANGES
End of build log:
${BUILD_LOG,maxLines=200}
''',
	        recipientProviders: [
		[$class: 'DevelopersRecipientProvider'],
	    ],
	        replyTo: '$DEFAULT_REPLYTO',
	        to: 'rblackwell@flatironinstitute.org'
        }
    }
}
